name:                calamity-admin-bot
version:             0.1.0.0
github:              "oscar-h64/calamity-admin-bot"
license:             BSD3
author:              "Oscar Harris"
maintainer:          "oscar@oscar-h.com"
copyright:           "2020 Oscar Harris"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/oscar-h64/calamity-admin-bot#readme>

dependencies:
- base >= 4.7 && < 5
- calamity
- polysemy
- polysemy-plugin
- di-polysemy
- text-show
- text
- microlens
- data-default
- colour
- time
- vector
- data-flags
- aeson
- yaml
- casing

default-extensions:
- OverloadedStrings
- OverloadedLabels
- NoImplicitPrelude
- DataKinds
- TypeApplications
- AllowAmbiguousTypes
- ScopedTypeVariables
- ConstrainedClassMethods
- FlexibleContexts
- TypeOperators
- ConstraintKinds
- GADTs
- DeriveGeneric

library:
  source-dirs: src
  ghc-options:
    - -O2
    - -fplugin=Polysemy.Plugin

executables:
  calamity-admin-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -fplugin=Polysemy.Plugin
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calamity-admin-bot

tests:
  calamity-admin-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calamity-admin-bot
