name:                discord-test
version:             0.1.0.0
github:              "oscar-h64/discord-test"
license:             BSD3
author:              "Oscar Harris"
maintainer:          "oscar@oscar-h.com"
copyright:           "2020 OscarHarris"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/oscar-h64/discord-test#readme>

dependencies:
- base >= 4.7 && < 5
- calamity
- polysemy
- polysemy-plugin
- di-polysemy
- text-show
- text
- lens
- data-default

default-extensions:
- OverloadedStrings
- OverloadedLabels
- NoImplicitPrelude
- DataKinds
- TypeApplications

library:
  source-dirs: src
  ghc-options:
    - -O2
    - -fplugin=Polysemy.Plugin

executables:
  discord-test-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -fplugin=Polysemy.Plugin
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discord-test

tests:
  discord-test-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discord-test
